---
.travis.yml:
  secure: "MARQfvJecdPQz1JCbXHasx7SmB2lxD7MqDLzSQ48Ky8wleh01brkvuN+v3OCtBTvuyGDK+QYvQD6ZH7+5Vs6LwlyMTeQm0qP8THskMJtlHKILpc+MvRKleNBoXnAlWjG/Owul1S10Tq7x7LfeQfAaG3k+l7qz+JMh/C7dAylwLv/hCjFr7WJ7pohKfA6+8tZxGRhcJDImKdQcp7N/iTaKopD3mXq9Swsy/WePa36jFIU9IsCHGmwJSxiQ+g79ybY5o81Or2MC4Xc4G7de5bWdFZg6r2aFqGXICetHYimVCHvEhmpGT6JfFMb+E/7hVAHHIBgwzHEKr6NHhZhJaebvjDx9BPtH+FsbRq1G0mMHRd72iHPptjXL36bMpmf+CmJJ2gjyMEgigqE/73+iqsfePjoj0yQdERRaZLE4rVDO7M/LHU1z8PP4OUVzDp1RuwTAPUO1IjpP/+gMxpSRrbAyWwkeWe+Cey3Z6YsEOmt6kyXVW8OdPTyg6C1Zk3YSOLZ5TpF7Uhad4Gyz8BGfz/ovxDuNC1hcenOJgANMRfglE8eFvYjjFo8mYD4KxydvvMTTt1V3j5nWlRrWQM8l9ZgOe7vtXFX4qGR35XDW6wyyDAWFzF3GkrZdbn/WBTaOiL+TsOFWJqqCT9W4rENVhGWhMGSvMVriMevrClvIoIHIPI="
  
.travis.yml:
  extras:
  - rvm: 2.4.1
    env: PUPPET_INSTALL_TYPE=agent CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/centos-7
    services: docker
    sudo: required
    bundler_args: --without development
    dist: trusty
  - rvm: 2.4.1
    env: PUPPET_INSTALL_TYPE=agent CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/debian-8
    services: docker
    sudo: required
    bundler_args: --without development
    dist: trusty
  - rvm: 2.4.1
    env: PUPPET_INSTALL_TYPE=agent CHECK=acceptance BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
    services: docker
    sudo: required
    bundler_args: --without development
    dist: trusty

